config/routes.rb
Rails.application.routes.draw do
  resources :videos

  get 'pages/about'

  get 'pages/contact'

  root 'videos#index'

end

app/models/video.rb
class Video < ActiveRecord::Base
	def next
		Video.where("id > ?", id).first
	end

	def prev
		Video.where("id < ?", id).last
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @videos = Video.all

    @next_video = @video.next
    @prev_video = @video.prev
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:wistia, :description, :title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

   <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/js/materialize.min.js"></script>
          
</head>
<body>


  <nav>
    <div class="nav-wrapper">
      <%= link_to "Home", root_path, :class => "brand-logo" %> 
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <li><a href="<%= root_path %>"><i class="mdi-action-view-list"></i></a></li>
        <li><a href="<%= pages_about_path %>"><i class="mdi-action-perm-identity"></i></a></li>
        <li><a href="<%= pages_contact_path%>"><i class="mdi-maps-place"></i></a></li>
      </ul>
      <ul class="side-nav" id="mobile-demo">
        <li><a href="<%= root_path %>"><i class="mdi-action-view-list"></i></a></li>
        <li><a href="<%= pages_about_path %>"><i class="mdi-action-perm-identity"></i></a></li>
        <li><a href="<%= pages_contact_path%>"><i class="mdi-maps-place"></i></a></li>
      </ul>
    </div>
  </nav>

  <div class="row">
  	<div class="col m10 offset-m1">
  		<%= yield %>
  	</div>
  </div>



<script>
	$(".button-collapse").sideNav();
</script>
</body>
</html>

app/views/pages/about.html.erb
<h3>About me</h3>
<div class="card z-depth-3">
	<div class="card-content white-text">
		<div class="col m6">
			<a class="twitter-timeline" href="https://twitter.com/tonkec_palonkec" data-widget-id="631423516093620224">Tweets by @tonkec_palonkec</a>
			<script>
			!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
			</script>
		</div>
		<div class="col m6">
			<div class="card-panel grey lighten-5 z-depth-1">
				<div class="row valign-wrapper">
					<div class="col m3">
						<%= image_tag "avatar.jpg", class: "circle responsive-img" %>
					</div>

					<div class="col m9">
						<span class="black-text">I don't know what to say. Let the world tell you more... :)</span>
					</div>
				</div><!--row-->
			</div><!--card-panel-->
		</div><!--col-m6-->
		
	</div><!--card-content-->
</div><!--card-->

app/views/pages/contact.html.erb
<h3>Let's connect</h3>
<div class="card z-depth-3">
	<div class="card-content">
		<p>Do you wanna stalk me? Find me on a map</p>
		<br />
		<div id="map"></div>
	</div>
</div>
<style>
      #map {
        width: 500px;
        height: 400px;
      }
    </style>
    <script src="https://maps.googleapis.com/maps/api/js"></script>
    <script>
      function initialize() {
        var mapCanvas = document.getElementById('map');
        var mapOptions = {
          center: new google.maps.LatLng(45.8167, 15.9833),
          zoom: 14,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        }
        var map = new google.maps.Map(mapCanvas, mapOptions)
       
      }
      google.maps.event.addDomListener(window, 'load', initialize);
    </script>

app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field">
    <%= f.text_field :wistia, :placeholder => "Link", :length=> '10' %>
  </div>
   <div class="input-field">
    <%= f.text_field :title, :placeholder => "Title", :length=> '20' %>
  </div>
  <div class="input-field">
    <%= f.text_area :description, :placeholder => "Description", :length=> '800', :class => "materialize-textarea" %>
  </div>
  <button class="btn waves-effect waves-light" type="submit" name="action">Submit</button>
  <a href="<%= videos_path %>" class="btn waves-effect waves-light" name="action">Back</a>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing video</h1>

<div class="card">
	<div class="card-content">
		<%= render 'form' %>
	</div>
</div>

app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing videos</h1>

<%= link_to new_video_path, :class => "btn-floating btn-large waves-effect waves-light red" do %>
  <i class="mdi-content-add"></i>
<% end %>

  <ul class="collapsible" data-collapsible="accordion">
    <% @videos.each do |video|  %>
    <li>
      <div class="collapsible-header">
        <i class="mdi-av-my-library-books"></i>
        <%= link_to video.title, video %>
        <span class="right">
          <%= link_to edit_video_path(video) do %>
          <i class="mdi-content-create"></i><% end%>
          <%= link_to video, method: :delete, data: {confirm: "Are you sure?"} do %>
          <i class="mdi-notification-event-busy"></i><%end %>
        </span>
      </div>
      <div class="collapsible-body"><p><%= video.description %></p></div>
    </li>
    <% end %>
  </ul>
        

app/views/videos/new.html.erb
<h1>New video</h1>


<div class="card">
	<div class="card-content">
		<%= render 'form' %>
	</div>
</div>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
	<div class="col m3">
		<div class="collection">
	       <%  @videos.each do |video| %>
	       	<%= link_to video.title, video, :class => "collection-item" %>
	       <% end %>
      </div>
	</div><!--col-->
	<div class="col m9">
		<div class="card blue-grey darken-1">
			<div class="card-image">
				<div id="wistia_<%= @video.wistia %>" style="height:387px;width:640px" data-video-width="640" data-video-height="360">
				  this is displayed if javascript is disabled
				</div>
			</div>
            <div class="card-content white-text">
              <button class="btn btn-primary" onclick="setPlaySpeed(0.75)">0.75x</button>
              <button class="btn btn-primary" onclick="setPlaySpeed(1)">1x</button>
              <button class="btn btn-primary" onclick="setPlaySpeed(1.25)">1.25x</button>
              <button class="btn btn-primary" onclick="setPlaySpeed(1.5)">1.5x</button>
              <button class="btn btn-primary" onclick="setPlaySpeed(2)">2x</button>
              <span class="card-title"><%= @video.title %></span>
              <p><%= @video.description %></p>
            </div>
            <div class="card-action">
              <%= link_to "Previous", @prev_video if !@prev_video.nil? %>
              <div class="right">
              	<%= link_to "Next", @next_video if !@next_video.nil? %>
              </div>
            </div>
          </div>
	</div>
</div>

<script src="http://fast.wistia.net/static/E-v1.js"></script>
<script>
	wistiaEmbed = Wistia.embed("<%= @video.wistia %>", {
	 videoQuality: "hd-only",
	 videoFoam: true
	});

	function setPlaySpeed (speed) {
		wistiaEmbed.playbackRate(speed)
	}
</script>